/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Skateboard.gltf
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Skateboard(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/Skateboard.gltf");
  // eslint-disable-next-line
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Skateboard"
          geometry={nodes.Skateboard.geometry}
          material={materials["Material.002"]}
        >
          <group name="Skateboard1">
            <mesh
              name="Mesh007"
              geometry={nodes.Mesh007.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              name="Mesh007_1"
              geometry={nodes.Mesh007_1.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              name="Mesh007_2"
              geometry={nodes.Mesh007_2.geometry}
              material={materials["Material.010"]}
            />
          </group>
          <mesh
            name="Skateboard2"
            geometry={nodes.Skateboard2.geometry}
            material={materials["Material.001"]}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("./models/Skateboard.gltf");
